ingest:
  version: demo
  api_key_env_var_name: COINGECKO_APIKEY
  endpoint: coins/{ids}/market_chart/range
  path_dict:  
    ids:
      - bitcoin
  param_dict:
    from: 1727740800 
    to: 1735689600
  data_granularity: daily
  save_path: /raw_data